### ISSUE TITLE
node: TChannel non-deterministically returns timeout error frame or timeout error

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#378]
This is probably the difference between a timeout in the outgoing request and a timeout in an incoming request.

It appears we have timeouts both inside the server and inside the client.

If we cared we could mark them as "client op timed out" vs "server op timed out".

**Comment by jcorbin** [comment]
Flap "fixed" in #379 since we want to handle local vs remote timeouts consistently (especially as in https://github.com/uber/tchannel/pull/379/files#diff-ac43f0ee5810be7a5e028517eca19300R246).

However it is indeed debt that our tests non-deterministically hit local vs remote rather than explicitly testing both.

**Comment by Raynos** [comment]
The tests have not flapped in a while. Closing.
