### ISSUE TITLE
v2 protocol errata: max call overhead is insane

### ISSUE THREAD

**Issue by jcorbin** [uber/tchannel#486]
The max call over head is insane, at 0x1ff25 bytes, aka (128Ki - 219)B:
- `0x00010` bytes fixed frame header
- `0x00001` byte flags
- `0x00004` bytes ttl
- `0x00019` bytes tracing
- `0x00100` bytes at most for service name (`1 + 0xff`)
- `0x1fe00` bytes at most for transport headers (`0xff * (1 + 0xff + 1 + 0xff)`)
- `0x00005` bytes for checksum
- `0x00002` bytes for length of arg1

We may want to impose some semantic limits on those...

**Comment by jcorbin** [comment]
I'll open the discussion by suggesting:
- limit transport header key length to 16 bytes (`0x10`)
- limit number of transport headers to 128 (0x80)

This gets us a maximum overhead of `0x89a5` bytes which leaves just under 32KiB for arg1 (2470 bytes off of 32KiB) in the worst case.

**Comment by jcorbin** [comment]
Also as a forward suggestion for protocol version past v2, moving headers to have binary coded keys (aka: `nh:1 (k:1 v~1){nh}`)

**Comment by Raynos** [comment]
:+1: for binary encoded keys.

:+1: for limits.

**Comment by Raynos** [comment]
On this note; to get deterministic behaviour for "arg1 must fit in a frame" I recommend we limit arg1 to 32kb or less so that irregardless of the number of transport headers it always fits in one frame.

Our autobahn proxy might add more transport headers whilst proxying and we would not want a valid incoming arg1 to become an invalid outgoing arg1 because we added transport headers.

**Comment by kriskowal** [comment]
Yes

**Comment by blampe** [comment]
+1

**Comment by mranney** [comment]
I like all of the limits that @jcorbin proposed. 128 headers, arg1 max 16KB, 16 bytes header key length.

**Comment by Raynos** [comment]
This is now fixed.

**Comment by Raynos** [comment]
This is now fixed.
