### ISSUE TITLE
GoLang: split up protocol errors from application errors within RoundTrip and handlers

### ISSUE THREAD

**Issue by dacamp** [uber/tchannel#516]
Spinning up an issue based off https://github.com/uber/tchannel/pull/509#discussion_r29540004.

My proposal for `RoundTrip` returned error:

> If there's an application error, RoundTrip should return nil (the transaction was successful). Then, inside the handler callback, *tchannel.InboundCall should have a struct field (or method) that returns the application error.
>
> This allow users to break out logical error handling between the protocol and the application levels.
>
> Sound reasonable?

**Comment by mmihic** [comment]
No, that's not correct.  The InboundCall and OutboundCall are low level primitives, and only express themselves in terms of arg2/arg3.  How application errors get converted into arg2/arg3 depends on the higher level RPC layers (the so-called "as" layers defined under thrift.md and json.md).

What we already do is correct - the low level primitives have a way of marking the response as being an application error (InboundCallResponse.SetApplicationError) which sets the appropriate protocol flag, and then you marshal the error however your higher level RPC layer expects.  On the return side, you get access to the flag indicating that the response is an application error (OutboundCallResponse.ApplicationError) and then you unmarshal that error however the higher level RPC layer expects.

Theoretically the low level protocol doesn't need to know anything about application errors - this is purely an application RPC concern.  We added the application flag soley so that middleware layers that sit between the low level primitives and the application can do logging/routing/metrics appropriately.

**Comment by mmihic** [comment]
What we should probably do is:

1. Eliminate the RoundTrip API.  This is a "convenience" API, but probably not worth maintaining in the face of streaming retries, application errors, and the like.  It's a bit more annoying for client code to interface directly with OutboundCall, but most client code will be using the higher level thrift/JSON RPC mechanisms anyway.

2. Make it so that you can call OutboundCall.ApplicationError prior to calling ReadArg2 (which means making it so that OutboundCall.ApplicationError waits for / processes the initial response fragment if it hasn't already been done).  That way you can check for application errors prior to unmarshalling the arg2 contents, and can use a type-specific unmarshaller appropriately.
