### ISSUE TITLE
Unify and Restructure

### ISSUE THREAD

**Issue by jcorbin** [uber/tchannel#77]
So far a structure like:
```
docs/...
node/...
python/...
go/...
c++/...
java/...
```

Most of what's currently written would be under node/, and we would merge in the .py efforts into python.

Later we'd add an integration test area.

We'd convert and land a markdown'd version of the google doc in docs/.

cc: @Raynos @mranney @sectioneight @kriskowal @jwolski

**Comment by jcorbin** [comment]
The more I think about this, the less I think that a shared repository, tag space, etc can work well... I really think we want to version and release the various language implementations separately.  I could barely see that working in a one-repo disjoint-branches scenario, but one conflated tree seems even more confusing.

I get the integration desires, but feel that should be addressed by a separate integration branch or repo which submodule (or subtree if you like) references the various implementations.

**Comment by kriskowal** [comment]
I also sense that tension. It might make sense to have `tchannel-node` etc repositories and jus track the shared spec or other artifacts on the `tchannel` name.

**Comment by sectioneight** [comment]
For reference, here is the gRPC layout: https://github.com/grpc/grpc/ -- of note: https://github.com/grpc/grpc/tree/master/src

I don't think it's unreasonable to track the changes in a single repository.

**Comment by Raynos** [comment]
I don't know how I feel about having all the languages in one git repo.

Firstly, you cannot have multiple node packages in one git repo and still do open source sanely. 

Every npm package needs to have it's own version number that is incremented atomically so you they can all respect semver. This means that every npm package needs it's own git tag version namespace.

With that said, we could put **one** npm project in a sub folder. But then we are going to have versioning hell. We node package will bump the major for every breaking change, expect node tchannel to be at version 10 within a month or two. This means that the node package needs the git tag space.

I would be ok with liberally bumping the version number every time any library (go, python, node) makes a breaking change, other libraries might not be ok with this and might want to "abuse" the major version number for the version of the protocol (which is silly).

Because node & python packages have different conventions around git this will get messy quite quickly. We could make it work for the node conventions if:

 - people can open issues about the node tchannel implementation on this github repository
 - we can create a new `vx.y.z` tag every time we change the version in tchannel node. If any other client/server in other languages also want that tag space we will have a lot of holes and will have to #dealwithit
 - The node repository will have its own self contained README. everything you need to be able to work with tchannel needs to be in that README.
 - The node repository will need its own travis integration. We really will need to create N travis projects so that the travis badge only shows node failures, not failures in any language.
 - To be able to contribute and develop on the node tchannel library you should only have to clone this repository and cd into node and do the normal node things. We do not want to end in a situation where you need to have all the C++, go, etc tooling to run the tests etc.

**Comment by Raynos** [comment]
@sectioneight grpc is a completely different design.

The node library is a binding to the C++ code. This means the C++ code & the node code has to be in repo or it just wont work.

Tchannel is different as you only need node, not node + C++. I have not looked at the rest of grpc but I presume most of the other libraries bind to the C code.

Actually the idiomatic way of doing this is to have a node library as it's own git repo with a `deps` folder and have the C++ code in there as a submodule.

**Comment by sectioneight** [comment]
Sure, but the node code doesn't bind to the objective-c code, and they happily sit next to each other.

**Comment by mranney** [comment]
Putting every language into one repo is very compelling to me. You can do git grep and also easily move through the timeline of releases across all platforms.

Surely the packaging details for each language could be contained within the subdirectory for that language, right?

The release process can be done with tags. Just prefix them with the directory name. Tags could be like: node-v1.0.0, python-v1.2.1, etc.

Does that not work?

**Comment by mranney** [comment]
I also really like the visibility we'll have over all the implementations in terms of PRs, issues, etc. I think it's better as one repo than as multiple repos.

**Comment by Raynos** [comment]
The `npm version` command creates `vx.y.z` tags.

You would need a separate new versioning process for tchannel. You would have to import tchannel differently from everything else and depend on `node-v1.0.0`. 

It could be done but it would be a poor experience and stick out like a sore thumb.

**Comment by mranney** [comment]
Well, that's too bad, but you could also just not use npm version. I didn't even know about it until just now.

**Comment by jcorbin** [comment]
Okay I've rebooted master:
- just a spartan README and LICENCE for now
- old master renamed to `old_node_master`

Next up:
- I'll do a conversion of the protocol google doc and open a PR to land it
- I'll do a subtree graft of v2 into `master:node/`
- someone else can do a subtree graft of an appropriate python branch into `master:python/`

In the future:
- we can have a common benchmarking suite in say `master:/benchmark`
- integration tests somewhere at root

**Comment by Raynos** [comment]
nice :)

**Comment by jcorbin** [comment]
Okay now here's the tricky part: I've renamed all prior v* tags to node-v*.

That means I neeed EVERYONE to run: `git fetch origin 'refs/tags/*:refs/tags/*' --prune` in their local repositories so we can head off getting zombie tags.

I'll blast a summary of such things to tchannel@ in a bit as well.

**Comment by jcorbin** [comment]
On the topic of node versioning concerns going forward:
- if it's useful / usable for npm, we can create new node-v* tags that point at a particular master:node/ tree object
- however that's probably a bit weird, so really we could create node-v* tags that point to specially crafted  commit objects
  - parent 1 would be prior special node-v* tagged commit
  - parent 2 would be the master commit from whence we're releasing
  - tree would be the master:node/ tree object from parent 2

I can easily script all of that, there's no need for people to have to manually do that git flow.

The same could be adapted if we release multiple node packages out of this repo (say splitting the parser / framing layer out for tcap).

If it's useful for python and others, we could do similar release tags for them.

**Comment by jcorbin** [comment]
PR out to bring in the protocol doc: #92
